[project]
name = "mcp-nilrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.11",
    "nilrag>=0.1.10",
    "uvicorn>=0.34.0",
]
